### ISSUE TITLE
订阅油管开播错误

### ISSUE THREAD

**Issue by sakurayang** [Mrs4s/VtuberBot#3]
![default](https://user-images.githubusercontent.com/11017232/54031792-b406ad80-41ea-11e9-9959-33dad63b422b.png)
![default](https://user-images.githubusercontent.com/11017232/54031836-d39dd600-41ea-11e9-92b7-4ca26f628a69.png)
![default](https://user-images.githubusercontent.com/11017232/54031852-dbf61100-41ea-11e9-897c-d7628ab372a4.png)

如图OTL

**Comment by Mrs4s** [comment]
查看的正确命令是
!订阅 查看 <Vtuber名字>
目前文档确实不足，我在忙考试，月底会加上文档的。

**Comment by sakurayang** [comment]
好
